name: Update Pull Request branch
author: juliangruber
description: 'Update a Pull Request from its base branch'
branding:
  icon: 'git-pull-request'
  color: purple
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  number:
    description: 'Pull Request number'
    required: false
  waitForPullRequestUpdated:
    description: 'Wait for the pull request to update before returning'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
